# Generated by Django 4.2.14 on 2024-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('cooks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='fav_recipes',
            field=models.ManyToManyField(null=True, related_name='recipes_fav', to='recipes.recipe'),
        ),
    ]
