# Generated by Django 4.2.14 on 2024-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0003_alter_cook_fav_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='pic',
            field=models.ImageField(default='no_picture.png', upload_to='recipes'),
        ),
    ]
