# Generated by Django 4.2.14 on 2024-08-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cooking_time', models.IntegerField(help_text='Please input how long it takes in minutes')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], max_length=20)),
                ('serves', models.PositiveIntegerField()),
                ('ingredients', models.CharField(help_text='Please input ingredients separated with commas', max_length=500)),
                ('methods', models.TextField()),
                ('cook_zero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooks.cook')),
            ],
        ),
    ]
