# Generated by Django 4.2.14 on 2024-08-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0003_alter_cook_fav_recipes'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_zero',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cooks.cook'),
        ),
    ]
