# Generated by Django 4.2.14 on 2024-08-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('v', 'V'), ('ve', 'VE'), ('fish', 'Fish'), ('contains_meat', 'Contains Meat'), ('versatile', 'Versatile')], default='versatile', max_length=50),
        ),
    ]
