# Generated by Django 4.2.14 on 2024-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('V', 'V'), ('Ve', 'VE'), ('Fish', 'Fish'), ('Contains Meat', 'Contains Meat'), ('Versatile', 'Versatile')], default='versatile', max_length=50),
        ),
    ]
